In [1]:
import numpy as np





In [2]:
array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


row_sums = array.sum(axis=1, keepdims=True)


normalized_array = array / row_sums



In [3]:
print("Original Array:")
print(array)

print("\nRow-Wise Normalized Array:")
print(normalized_array)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row-Wise Normalized Array:
[[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]
 [0.29166667 0.33333333 0.375     ]]
